### ISSUE TITLE
Convert to external project

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/libzmq_catkin#1]
This is a hard fork with all files copied in. This is highly discouraged. Please convert to external project as a catkin wrapper. 

Local libraries/wrappers can then use the external project already.

**Comment by VladimirIvan** [comment]
The main stream repo seems to include the ros wrapper already.

There seem to be `external`, `m4`, `unittest`, `RELICENSE` added and `tweetnacl` missing.
Did you add these or are they legacy code? What is the diff?

**Comment by Leph** [comment]
The use of external project is done in "branch external_project".
This also include the c++ header binding and enable the new draft api for UDP multicast.

Can we change the name of the repo to uoe_zmq ?

**Comment by wxmerkt** [comment]
Awesome. Repository is renamed as well
